[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
requires-python = ">=3.10"
authors = [{ name = "Christoph Heindl"}]
name = "bilateral"
dynamic = ["dependencies", "optional-dependencies", "version"]

[project.urls]
Homepage = "https://github.com/cheind/py-bilateral-filter"

[tool.setuptools.packages.find]
where = ["."] 
include = ["bilateral*"]

[tool.setuptools.dynamic]
version = {attr = "bilateral.__version__.VERSION"}
dependencies = { file = ["requirements.in"] }
optional-dependencies.dev = { file = ["dev-requirements.in"] }
